# We have this so that one doesn't need to manually pass
# --target=bpfel-unknown-none -Z build-std=core when running cargo
# check/build/doc etc.
#
# NB: this file gets loaded only if you run cargo from this directory, it's
# ignored if you run from the workspace root. See
# https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure
#
# NB-2: cargo xtask docs currently relies on this file existing.
[build]
target = "bpfel-unknown-none"

[unstable]
build-std = ["core"]
