name: build-aya-bpf

on:
  push:
    branches:
      - main
      - ci

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - arm
          - riscv64
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rust-src

      - uses: Swatinem/rust-cache@v2

      - name: Prereqs
        run: cargo install bpf-linker

      - name: Build
        env:
          CARGO_CFG_BPF_TARGET_ARCH: ${{ matrix.arch }}
        run: |
          cargo build-bpfel -p aya-bpf --verbose
          cargo build-bpfeb -p aya-bpf --verbose
          cargo build-bpfel -p aya-log-ebpf --verbose
          cargo build-bpfeb -p aya-log-ebpf --verbose
